### ISSUE TITLE
Example SDF-File

### ISSUE THREAD

**Issue by dketterer** [andreasBihlmaier/gazebo2rviz#21]
Hi Andreas,

I am trying to make to send my own model to rviz and I can see how gazebo2rviz sends out messages to `/visualization_marker` but it seems I have no TF in the SDF file and no TF is send out with the tfBroadcaster. Do you have a link to a minimal example SDF that is working for you? I think I can find the problem with my own files from there.

Thanks in advance.
Daniel

**Comment by tik0** [comment]
In the gazebo model database

**Comment by tik0** [comment]
In the gazebo model data base you can find the [coke_can](https://github.com/osrf/gazebo_models/tree/master/coke_can), which works for me as a minimal example. However, I am also using the fork from ANYbotics, which looks more mature.

Some of the models do not work properly like the [cafe_table](https://github.com/osrf/gazebo_models/tree/master/cafe_table). While you can load it properly in Gazebo, you wont see textures in rviz. This is because of the messed-up texture locations in the dae file.

**Comment by andreasBihlmaier** [comment]
@tik0 thank you for jumping in here. I'll try to merge improvements done by others in recent years soon.
@dketterer see http://andreasbihlmaier.github.io/2014/02/19/gazebo2rviz.html for an old example that should still work. There are known limitations how the models need to be structured to work.
